### DISCUSSION TITLE
F-Droid can't build

### DISCUSSION THREAD

**Discussion by licaon-kter** [T8RIN/ImageToolbox#151] [Q&A] [answered]
...reproducible

ref: https://monitor.f-droid.org/builds/log/ru.tech.imageresizershrinker/45#site-footer

**Comment by T8RIN** [comment]
What's went wrong?

**Comment by T8RIN** [comment]
I'm still using github actions(

**Comment by licaon-kter** [comment]
46 built fine: https://monitor.f-droid.org/builds/log/ru.tech.imageresizershrinker/46#site-footer :tada:

**Comment by licaon-kter** [comment]
And again https://monitor.f-droid.org/builds/log/ru.tech.imageresizershrinker/66#site-footer :(

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/2ee4d8e8ae8e9486ca3237fbc30c2c636fe164c6

**Reply by T8RIN** [reply]
Why this could happen?

**Reply by T8RIN** [reply]
I'm added native cpp libs but they were copied from here

**Reply by T8RIN** [reply]
https://github.com/cats-oss/android-gpuimage

**Reply by licaon-kter** [reply]
And those build reproducible too? Every time you test?

**Reply by T8RIN** [reply]
I don't understand what you mean, to be honest :(

**Reply by licaon-kter** [reply]
As the log say: https://monitor.f-droid.org/builds/log/ru.tech.imageresizershrinker/66#site-footer the fdroid built `libyuv-decoder.so` are not identical with yours...

**Reply by T8RIN** [reply]
I've built it with GitHub actions, what can cause those?(

**Reply by T8RIN** [reply]
How to fix this?

**Reply by licaon-kter** [reply]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/790c389995c003562a59ddd898df063018f81b5e

ref: https://monitor.f-droid.org/builds/log/ru.tech.imageresizershrinker/67#site-footer

**Reply by T8RIN** [reply]
I don't know what i can do with this

**Reply by linsui** [reply]
The build-id of libyuv-decoder.so is different. See https://f-droid.org/docs/Reproducible_Builds/#ndk-build-id.

**Reply by T8RIN** [reply]
I added this now, did it work?

**Reply by linsui** [reply]
We need to build these libs from source first. https://github.com/T8RIN/ImageToolbox/tree/master/avif-coder/src/main/cpp/lib How can I build them?

**Reply by T8RIN** [reply]
https://github.com/strukturag/libheif this one

**Reply by linsui** [reply]
Could you please add the build script so that we can build the same binary?

**Reply by T8RIN** [reply]
How?(

**Reply by linsui** [reply]
How did you build it? From which commit?

**Reply by T8RIN** [reply]
Just used this https://github.com/awxkee/avif-coder

**Reply by linsui** [reply]
They doesn't provide build script either. Only binaries...

**Reply by T8RIN** [reply]
I see, i think they needed to be compiled using C ides, so AS cant do that

**Reply by T8RIN** [reply]
@linsui @licaon-kter is now the app can be published again?

**Comment by shuvashish76** [comment]
Any updates? Missing multiple releases 😶‍🌫️

**Reply by T8RIN** [reply]
Unfortunately no :( i don't know how to add those libs to gradle to be built automatically, because those libs are compiled from non android cpp code

**Reply by linsui** [reply]
I thought the proper way is using cmake but you can add a build script and run it in gradle.

**Comment by IzzySoft** [comment]
Btw, build of 2.3.0 will fail, too, see #412

**Comment by T8RIN** [comment]
@licaon-kter hi, how to update yml according to #412 ?

**Reply by licaon-kter** [reply]
This fail here is not related to the other non-FOSS stuff.. here one needs to update the recipe to rebuild all this stuff, right?

**Reply by T8RIN** [reply]
This one https://github.com/T8RIN/ImageToolbox/issues/412#issuecomment-1702637180

**Reply by T8RIN** [reply]
> This fail here is not related to the other non-FOSS stuff.. here one needs to update the recipe to rebuild all this stuff, right? 

I've added pure foss build, which will be accepted on f-droid

**Reply by IzzySoft** [reply]
What LK and I meant was: there are 2 problems here; just solving one won't be sufficient. Without having the build itself fixed, the part I've sent you with the other issue won't help bringing the app back – and vice versa. Which is why I didn't just go ahead committing my part, but rather offered it for integration here. Both issues need to be addressed in order to have the build succeed, @T8RIN.

**Reply by T8RIN** [reply]
> What LK and I meant was: there are 2 problems here; just solving one won't be sufficient. Without having the build itself fixed, the part I've sent you with the other issue won't help bringing the app back – and vice versa. Which is why I didn't just go ahead committing my part, but rather offered it for integration here. Both issues need to be addressed in order to have the build succeed, @T8RIN.

You mean i need to solve the diff? Maybe now it will be solved, so i'll wait for fdroid build

**Reply by licaon-kter** [reply]
Why don't you use `implementation 'com.github.awxkee:jxlcoder:1.0.5'` and `implementation 'com.github.awxkee:avif-coder:1.0.19'` directly instead of copying them locally? did you modify them?

**Reply by T8RIN** [reply]
Yes, i've modified the source 👀

**Reply by licaon-kter** [reply]
Then again I'm not sure where https://github.com/awxkee/jxl-coder/tree/master/jxlcoder/src/main/cpp/lib all these .so's are coming from  to begin with :(

I'm trying now to rebuild https://github.com/awxkee/avif-coder since it has clear instructions and scripts 

but not sure how to do the same for https://github.com/awxkee/jxl-coder :(

**Reply by T8RIN** [reply]
I will ask dev now

**Reply by T8RIN** [reply]
Btw you don't need jxl reference, because foss flavor doesn't have it 👀

**Reply by T8RIN** [reply]
Btw you don't need jxl reference, because foss flavor doesn't have it 👀

**Reply by licaon-kter** [reply]
Yeah, saw something, didn't get to that point yet... still messing with avif-coder :)

**Reply by T8RIN** [reply]
> Yeah, saw something, didn't get to that point yet... still messing with avif-coder :)
> 

If it is too hard, i can just remove the avif-coder from the foss version, with the new flavor system this will cost me just two clicks 🙈

**Reply by licaon-kter** [reply]
What is this used for? Showing pictures? Conversion? Videos?

**Reply by T8RIN** [reply]
> What is this used for? Showing pictures? Conversion? Videos?

It's used for showing and convert to three formats : avif/heic/heif

**Reply by licaon-kter** [reply]
It builds fine now, trying to integrate it :tada: brb

**Reply by T8RIN** [reply]
Great!

**Reply by licaon-kter** [reply]
```
  - versionName: 2.3.1
    versionCode: 85
    commit: 47af5c6b0742748100fc6c4cb8aedc4b0d4837bb
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y -t bullseye-backports cmake
      - apt-get install -y build-essential meson nasm ninja-build
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - foss
    srclibs:
      - avif-coder@1.0.19
    prebuild:
      - sed -i -e '/google-services/d' -e '/firebase/d' ../build.gradle.kts
      - sed -i -e '/mlkit/,+14d' -e '/google-services/d' -e '/firebase/d' build.gradle.kts
    scandelete:
      - avif-coder
      - jxlcoder
    build:
      - pushd $$avif-coder$$
      - sed -i -e "s/-i ''/-i/" build_x265.sh
      - NDK_PATH=$$NDK$$ INCLUDE_X86=yes bash build_all.sh
      - popd
      - cp $$avif-coder$$/avif-coder/src/main/cpp/lib/armeabi-v7a/* ../avif-coder/src/main/cpp/lib/armeabi-v7a/
      - cp $$avif-coder$$/avif-coder/src/main/cpp/lib/x86_64/* ../avif-coder/src/main/cpp/lib/x86_64/
      - cp $$avif-coder$$/avif-coder/src/main/cpp/lib/arm64-v8a/* ../avif-coder/src/main/cpp/lib/arm64-v8a/
    ndk: r25b
```

and **srclibs/avif-coder.yml**
```
RepoType: git
Repo: https://github.com/awxkee/avif-coder.git
```

buuut, the issue will be next that of reproducibility...basically you'll need to rebuild it and hopefully `avif-coder` is reproducible? :( :)

**Reply by T8RIN** [reply]
Didn't get it about avif, can you reexplain please? :(

**Reply by licaon-kter** [reply]
OK, so, your FOSS APKs use "random" libs from the internet: https://github.com/T8RIN/ImageToolbox/tree/47af5c6b0742748100fc6c4cb8aedc4b0d4837bb/avif-coder/src/main/cpp/lib/arm64-v8a

We need to rebuild them (see recipe above) or defer to the maven uploaded ones (hopefully those are free and clean): `implementation 'com.github.awxkee:avif-coder:1.0.19'`

But, rebuilding them brings variability, do you build stuff under clean Debian or just use a random Mac device?

So, next move, can you use `implementation 'com.github.awxkee:avif-coder:1.0.19'` ?

**Reply by T8RIN** [reply]
Hmm, i think i can use this dependency for foss flavor and my modified one for others

**Reply by T8RIN** [reply]
I spent 3 hours, but, now the foss flavor must rely on the remote avif-coder

**Reply by T8RIN** [reply]
@licaon-kter i've added remote dep in 2.3.2, so, can i be on f-droid now?

**Comment by licaon-kter** [comment]
Ok, almost there
```
│ │ │   --- image-toolbox-2.3.2-foss-universal/smali/ca/a.smali
│ │ ├── +++ ru.tech.imageresizershrinker_87/smali/ca/a.smali
│ │ │ @@ -9995,15 +9995,15 @@
│ │ │      .line 1560
│ │ │      .line 1561
│ │ │      invoke-virtual {v1, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
│ │ │  
│ │ │      .line 1562
│ │ │      .line 1563
│ │ │      .line 1564
│ │ │ -    const-string v0, " 2.3.2_foss (87)"
│ │ │ +    const-string v0, " 2.3.2-foss (87)"
...
│ │ │ │ │ │ │   --- image-toolbox-2.3.2-foss-universal/smali/ru/tech/imageresizershrinker/presentation/crash_screen/CrashActivity.smali
│ │ │ │ │ │ ├── +++ ru.tech.imageresizershrinker_87/smali/ru/tech/imageresizershrinker/presentation/crash_screen/CrashActivity.smali
│ │ │ │ │ │ │ @@ -279,15 +279,15 @@
│ │ │ │ │ │ │      .line 115
│ │ │ │ │ │ │      .line 116
│ │ │ │ │ │ │      invoke-static {v8, v2, v1, v3, p1}, Lo/h;->J(Ljava/lang/StringBuilder;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
│ │ │ │ │ │ │  
│ │ │ │ │ │ │      .line 117
│ │ │ │ │ │ │      .line 118
│ │ │ │ │ │ │      .line 119
│ │ │ │ │ │ │ -    const-string p1, "), App: 2.3.2_foss (87)\n\n"
│ │ │ │ │ │ │ +    const-string p1, "), App: 2.3.2-foss (87)\n\n"
...
│ │ │ │ │ │ │ │   --- image-toolbox-2.3.2-foss-universal/smali/ru/tech/imageresizershrinker/presentation/main_screen/viewModel/MainViewModel.smali
│ │ │ │ │ │ │ ├── +++ ru.tech.imageresizershrinker_87/smali/ru/tech/imageresizershrinker/presentation/main_screen/viewModel/MainViewModel.smali
│ │ │ │ │ │ │ │ @@ -397,15 +397,15 @@
│ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │      .line 16
│ │ │ │ │ │ │ │      .line 17
│ │ │ │ │ │ │ │      .line 18
│ │ │ │ │ │ │ │      move-result v1
│ │ │ │ │ │ │ │  
│ │ │ │ │ │ │ │      .line 19
│ │ │ │ │ │ │ │ -    const-string v2, "2.3.2_foss"
│ │ │ │ │ │ │ │ +    const-string v2, "2.3.2-foss"
...
│ │ │   --- image-toolbox-2.3.2-foss-universal/smali/ua/u1.smali
│ │ ├── +++ ru.tech.imageresizershrinker_87/smali/ua/u1.smali
│ │ │ @@ -506,15 +506,15 @@
│ │ │  
│ │ │      .line 203
│ │ │      .line 204
│ │ │      .line 205
│ │ │      move-result-object v16
│ │ │  
│ │ │      .line 206
│ │ │ -    const-string v17, "2.3.2_foss (87)"
│ │ │ +    const-string v17, "2.3.2-foss (87)"
```

while the source code has suffix `-foss` and F-Droid builds that: https://github.com/T8RIN/ImageToolbox/blob/2.3.2/app/build.gradle.kts#L68

Your hosted APKs have `_foss` ? @T8RIN https://github.com/T8RIN/ImageToolbox/releases/tag/2.3.2

**Reply by T8RIN** [reply]
They should be -foss , i've accidentally picked _foss, but then changed to -foss in the 2.3.3

**Reply by licaon-kter** [reply]
Will rebuild then...

**Reply by T8RIN** [reply]
Can you change app name to image toolbox (resizer) also?

**Reply by T8RIN** [reply]
And i added new metadata to fastlane

**Reply by T8RIN** [reply]
> Will rebuild then...

@licaon-kter is it worked?

**Reply by licaon-kter** [reply]
Will rebuild THEN... in the future.... when you release a 2.3.3 or upload fixed APKs with `-foss` to 2.3.2

In the meantime... nothing changed.

**Reply by T8RIN** [reply]
> Will rebuild THEN... in the future.... when you release a 2.3.3 or upload fixed APKs with `-foss` to 2.3.2
> 
> In the meantime... nothing changed.

Oh, okay, sorry for misunderstanding (

I will drop 2.3.3-alpha01 today i think

**Reply by T8RIN** [reply]
https://github.com/T8RIN/ImageToolbox/releases/tag/2.3.3-alpha01 here it is :)

**Reply by licaon-kter** [reply]
rebuilding now, just a heads up ,don't forget to bump versionCode, current one [is still `87`](https://github.com/T8RIN/ImageToolbox/blob/2.3.3-alpha01/app/build.gradle.kts#L25) like [`2.3.2` had](https://github.com/T8RIN/ImageToolbox/blob/2.3.2/app/build.gradle.kts#L25)

**Reply by licaon-kter** [reply]
`2.3.3-alpha01` is repro... but only if I check it manually

I can't automate it because I can't pickup the path to your binary

`https://github.com/T8RIN/ImageToolbox/releases/download/2.3.3-alpha01/image-toolbox-2.3.3-alpha01-foss-universal.apk`

I can replace `%v` with versionName, but that's `2.3.3-alpha01-foss` because of the flavor suffix, hence that `/2.3.3-alpha01/` part can't be templated from anything

My quick idea, drop the `-foss` versionName suffix, but keep the apk name one, so we can use:

``https://github.com/T8RIN/ImageToolbox/releases/download/%v/image-toolbox-%v-foss-universal.apk``

**Reply by T8RIN** [reply]
i can't do so i think, because i added this to version name specially for quick identifying

**Reply by T8RIN** [reply]
what else can we do?

**Reply by T8RIN** [reply]
No other solution ? :( I can do that if it's really one way...

**Reply by licaon-kter** [reply]
There are only 2 variables/templates that F-Droid can use `%v` for versionName and `%c` for versionCode.

**Reply by T8RIN** [reply]
> There are only 2 variables/templates that F-Droid can use `%v` for versionName and `%c` for versionCode.

Why can't we use versionName then?

**Reply by linsui** [reply]
We need 2.3.3-alpha01 but it's not the version name. The version name is 2.3.3-alpha01-foss.

**Reply by T8RIN** [reply]
> We need 2.3.3-alpha01 but it's not the version name. The version name is 2.3.3-alpha01-foss.

Why then it can't be just used as is? Izzy on droid handle that easily :(

**Reply by linsui** [reply]
If we don't need reproducible build we can handle this...

**Reply by T8RIN** [reply]
> If we don't need reproducible build we can handle this...

What does it mean? :(

**Reply by IzzySoft** [reply]
> Izzy on droid handle that easily :(

My updater does not need to build from source, it just picks the latest APK.

> What does it mean? :(

With reproducible builds, F-Droid would ship the APK signed by you – so cross-updates are possible (you could e.g. push "emergency updates" if your build at F-Droid got stuck or the like). Without, it would generate a dedicated key for signing your app, so cross-updates would not be possible. I'd strongly recommend using reproducible builds if possible.

**Reply by T8RIN** [reply]
> > Izzy on droid handle that easily :(
> 
> My updater does not need to build from source, it just picks the latest APK.
> 
> > What does it mean? :(
> 
> With reproducible builds, F-Droid would ship the APK signed by you – so cross-updates are possible (you could e.g. push "emergency updates" if your build at F-Droid got stuck or the like). Without, it would generate a dedicated key for signing your app, so cross-updates would not be possible. I'd strongly recommend using reproducible builds if possible.

Okeydoke, i will change then

**Reply by T8RIN** [reply]
okay, added this

**Reply by IzzySoft** [reply]
Great, thanks!

In this context, as we had several occasions (in F-Droid as well as in my repo), please take good care for your keystore: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) :wink:

**Reply by T8RIN** [reply]
Released a new stable version where this is implemented 👀 @licaon-kter

**Reply by licaon-kter** [reply]
testing now, brb

**Reply by licaon-kter** [reply]
@T8RIN thanks https://gitlab.com/fdroid/fdroiddata/-/commit/f3be8ba255f1f3f1ba84a7f3c75a30445d14ebaa

**Reply by T8RIN** [reply]
🐸❤️

**Reply by T8RIN** [reply]
@licaon-kter also when it will be available at the f-droid?👀

**Reply by licaon-kter** [reply]
@T8RIN https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

**Reply by linsui** [reply, marked as answer]
It's available now.

**Reply by T8RIN** [reply]
Great!

**Reply by T8RIN** [reply]
@licaon-kter hi, i noticed, that for some reason new fastlane screenshots and description doesn't appear on the f-droid app page, at least on the site, what's went wrong here? :(

**Reply by licaon-kter** [reply]
you had 2 JPG files(https://github.com/T8RIN/ImageToolbox/commit/811c858e3080a2be890628b143a6bc8c7d000870#diff-0e01beb746633e7827aeac7c5376452173f6274899f081a4de077f30540b63b0), you deleted and replaced them with PNGs

known issue, fdroidserver didn't clean up: https://gitlab.com/fdroid/fdroidserver/-/issues/490 :(

will try a manual clean up next: https://gitlab.com/fdroid/admin/-/issues/377#note_1665510324

**Reply by T8RIN** [reply]
> you had 2 JPG files(https://github.com/T8RIN/ImageToolbox/commit/811c858e3080a2be890628b143a6bc8c7d000870#diff-0e01beb746633e7827aeac7c5376452173f6274899f081a4de077f30540b63b0), you deleted and replaced them with PNGs
> 
> known issue, fdroidserver didn't clean up: https://gitlab.com/fdroid/fdroidserver/-/issues/490 :(
> 
> will try a manual clean up next: https://gitlab.com/fdroid/admin/-/issues/377#note_1665510324

Okay, i'll wait...

**Comment by T8RIN** [comment]
Hi, @licaon-kter , why 2.6.0 isn't available on fdroid yet?

**Reply by linsui** [reply]
The version info is moved to another file so the auto update doesn't work. I fixed that but it's not reproducible. https://gitlab.com/linsui/fdroiddata/-/jobs/6089395201

**Reply by T8RIN** [reply]
What's happened again?

**Reply by linsui** [reply]
I don't know. Maybe @licaon-kter will take a look.

**Reply by linsui** [reply]
You can check the diff with diffoscope.

**Reply by T8RIN** [reply]
I see something with native libs

**Reply by linsui** [reply]
As I guess, the ndk build id is different. Please disable ndk build id for libWatermark.so. See https://f-droid.org/docs/Reproducible_Builds/#ndk-build-id.

**Reply by T8RIN** [reply]
Okay, i will try to do so, anyway idk why watermark have own cpp file, it's not used as i remember

**Reply by T8RIN** [reply]
Added this, hope it will help

**Reply by linsui** [reply]
Thanks! Let's see if the next version is reproducible.

**Comment by T8RIN** [comment]
@linsui, @licaon-kter how it's going on 2.6.1-alpha01 ? 👀

**Reply by licaon-kter** [reply]
will test now

**Reply by T8RIN** [reply]
How it's going?

**Reply by licaon-kter** [reply]
Still different, will extract diff asap

**Reply by licaon-kter** [reply]
rebuilt today and it's repro :tada: ooodddlyyyy

```
  - versionName: 2.6.1-alpha01                                                                                                 
    versionCode: 118                                                                                                           
    commit: 3d73cf6a47e790d145542ab8e9b6d8bd69bab499                                                                           
    subdir: app                                                                                                                
    sudo:                                                                                                                      
      - apt-get update                                                                                                         
      - apt-get install -y openjdk-17-jdk-headless                                                                             
      - update-java-alternatives -a                                                                                            
    gradle:                                                                                                                    
      - foss                                                                                                                   
    output: build/outputs/apk/foss/release/image-toolbox-*-foss-universal-release-unsigned.apk                                 
    prebuild:                                                                                                                  
      - sed -i -e '/google-services/d' -e '/firebase/d' ../build.gradle.kts                                                    
      - sed -i -e '/mlkit/,+14d' -e '/google-services/d' -e '/firebase/d' build.gradle.kts                                     
    scandelete:                                                                                                                
      - build-logic
```
