### ISSUE TITLE
Proprietary components added with latest release: blockers for F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [T8RIN/ImageToolbox#412]
Quoting the release notes of 2.3.0:

> Added Firebase Analytics and Crashlytics which also can be disabled

This will disable updates for your app at F-Droid (where proprietary components are not allowed). For your listing in my repo, the same applies now:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeComp,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet
* ML Kit (/com/google/mlkit): NonFreeComp,Tracking

7 offenders.
```

which is too much. With the next sync, v2.3.0 will be removed from my repo and updates disabled until this issue is resolved (and a newer release with this issue fixed is available). Everything marked `NonFreeComp` is an absolute show-stopper for F-Droid; for my repo it's a bit relaxed, but 5 `NonFreeComp` are too much as well – especially when accompanied with multiple `Tracking` and more.

As your app is set up with reproducible builds at F-Droid, you'll need to fix that for your own builds as well – this is nothing that can be "patched out" at F-Droid.

**Comment by T8RIN** [comment]
Then i need to remove Crashlytics and Analytics? An ML kit is definitely needed for the new background remover

**Comment by T8RIN** [comment]
And also why if the user can just disable that collection, or should i create a special version where it will be disabled

**Comment by T8RIN** [comment]
Can i use at least acra then?

**Comment by T8RIN** [comment]
This one instead of firebase, is it ok then? https://github.com/ACRA/acra

**Comment by IzzySoft** [comment]
Using ACRA (configured opt-in) is fine, yes – that's what the F-Droid client uses as well. But MLKit is still a show-stopper for F-Droid.org. As is Play Store In App Review.

**Comment by T8RIN** [comment]
Okay, if i remove firebase, can i be present in your repo? Because i definitely can't remove mlkit :( the same for in app review i think

**Comment by T8RIN** [comment]
?

**Comment by T8RIN** [comment]
Okay, i will try to do so, firstly i want to set up ACRA, abd remove firebase 🐸

**Comment by T8RIN** [comment]
I'm on the way of adding product flavors

**Comment by T8RIN** [comment]
aaaaaaaaaaaaaaaaaaaaand yes, that's definitely works, now i can introduce pure foss clean build flavor :))))

**Comment by IzzySoft** [comment]
That's fantastic! Please give me a ping once the first release has those APKs attached, so I can adjust my config here to pick those with future releases, and re-enable updates :star_struck:

**Comment by T8RIN** [comment]
> That's fantastic! Please give me a ping once the first release has those APKs attached, so I can adjust my config here to pick those with future releases, and re-enable updates :star_struck:

Okay 👀

**Comment by shuvashish76** [comment]
> With the next sync, v2.3.0 will be removed from my repo and updates disabled until this issue is resolved (and a newer release with this issue fixed is available)

@IzzySoft It's still available.

**Comment by IzzySoft** [comment]
@shuvashish76 no, it was pulled in again. I did only disable the daily check, in the hope it would be solved before the monthly check would run again (apps rarely updated are only checked monthly). Unfortunately, this was not the case. I've just removed the APK again now and will trigger a sync manually, so it should be gone again in a few minutes.

@T8RIN I hope you can make it before the next monthly check kicks in, or I'll have to disable updates entirely. Which could then mean the entire thing might be forgotten until someone pings me again about it, and your app never be updated :scream: (no pressure, just a friendly hint :wink:)

**Comment by T8RIN** [comment]
> @shuvashish76 no, it was pulled in again. I did only disable the daily check, in the hope it would be solved before the monthly check would run again (apps rarely updated are only checked monthly). Unfortunately, this was not the case. I've just removed the APK again now and will trigger a sync manually, so it should be gone again in a few minutes.
> 
> @T8RIN I hope you can make it before the next monthly check kicks in, or I'll have to disable updates entirely. Which could then mean the entire thing might be forgotten until someone pings me again about it, and your app never be updated :scream: (no pressure, just a friendly hint :wink:)

When will this sync be? Cuz i can publish foss release right now, it works as expected, but i will need to publish new release which i haven't finished yet, can i do this by the pre release?

**Comment by T8RIN** [comment]
@IzzySoft here it is https://github.com/T8RIN/ImageToolbox/releases/tag/2.3.1

**Comment by IzzySoft** [comment]
That looks good, thanks! Updated the config here to only accept APKs matching `/foss-arm64-v8a/i`, manually triggered a check, scan results look fine – updates re-enabled :partying_face:

So you're back on daily schedule now. Check happens around 5:30 pm UTC (summertime), sync is usually complete around 6 pm UTC then.

----

As all looks fine so far, the YAML for F-Droid.org still needs to be adjusted: `gradle: foss`, and the `binary:` values accordingly. That would be a task for #151 then I guess. For possible transfer:

```yaml
Categories:
  - Graphics
License: Apache-2.0
AuthorName: Malik Mukhametzyanov
AuthorEmail: open.t8rin@internet.ru
SourceCode: https://github.com/T8RIN/ImageToolbox
IssueTracker: https://github.com/T8RIN/ImageToolbox/issues
Translation: https://hosted.weblate.org/engage/image-resizer
Changelog: https://github.com/T8RIN/ImageToolbox/releases
Donate: https://qiwi.com/n/T8RIN

AutoName: Image Toolbox (Resizer)

RepoType: git
Repo: https://github.com/T8RIN/ImageToolbox.git
Binaries: https://github.com/T8RIN/ImageToolbox/releases/download/%v/image-toolbox-%v-foss-universal.apk

Builds:
  - versionName: 2.3.1-foss
    versionCode: 85
    commit: 47af5c6b0742748100fc6c4cb8aedc4b0d4837bb
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - foss

AllowedAPKSigningKeys: 20d7689de0874f00015ea3e31fa067c15c03457d362d41d5e793db3a864fa534
    
AutoUpdateMode: None
UpdateCheckMode: Tags
CurrentVersion: 2.3.1-foss
CurrentVersionCode: 85
```

(I've skipped the older build blocks here; relevant changes are the new repo URL, the `Binaries:` line, the new build block, and `CurrentVersion`/ `CurrentVersionCode`.) As the build was broken before for other reasons, I'd prefer some packager with more experience will tackle that part.
